name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Build"
        run: echo "THIS IS THE README" >> README.md && echo "some text" >> sample.txt 
      - name: "Get Version"
        id: version
        run: |
          echo "VERSION=$(date +"%Y/%m/%d-(%H:%M:%S)")" >> $GITHUB_OUTPUT

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{steps.version.VERSION}}"
          prerelease: false
          title: "${{steps.version.outputs.VERSION}}"
          files: |
            README.md
            *.txt
